MULTIPOINT_CONTROL_UNIT=attiny85
AVRDUDEMCU=t85
CC=/usr/bin/avr-gcc
CFLAGS=-g -Os -Wall -mcall-prologues -mmcu=$(MULTIPOINT_CONTROL_UNIT)
OBJ2HEX=/usr/bin/avr-objcopy
AVRDUDE=/usr/local/bin/avrdude
LIBS=-I /home/pi/dev/lib/c
TARGET=code
F_CPU = 8000000UL 
BAUD  = 19200
CPPFLAGS = -std=c++11 -DF_CPU=$(F_CPU) -DBAUD=$(BAUD) -I. 
